### ISSUE TITLE
[Feature] Support for grep

### ISSUE THREAD

**Issue by syl20bnr** [syohex/emacs-helm-ag#117]
Do you think it is possible to support grep in helm-ag ?

Right now in spacemacs with use helm-ag for `ag`, `pt` and `ack`, we even use it instead of `helm-projectile`, this is great because we can enjoy the `C-c C-e` feature of `helm-ag`. Thanks to `helm-ag` we can unify search in files, in opened buffers, in current file and in current project.

The only thing we don't support with `helm-ag` is grep, it would be wonderful to be able to have this backend supported.

**Comment by syohex** [comment]
> Do you think it is possible to support grep in helm-ag ?

Yes, it is. But it is just `helm-do-grep`.

**Comment by syl20bnr** [comment]
This is what we use currently my question was to really about supporting grep in helm-ag in order to have the same `C-c C-e` available to edit the results.

**Comment by syohex** [comment]
Ah, I misread.

However supporting `grep` makes maintenance hard, because there are many implementations, GNU grep, FreeBSD grep, NetBSD grep, OpenBSD grep, MacOSX grep etc. And helm-ag cannot provide some feature(`ignore pattern` etc) for some implementations.

So I decide not to support `grep` as backend.

Please use `ag` or `ack` or `pt` as backend.
