### ISSUE TITLE
Search by file types

### ISSUE THREAD

**Issue by bgvianyc** [syohex/emacs-helm-ag#161]
ag supports search by file types ie:

```
ag --html needle
```
  Searches for 'needle' in files with suffix .htm, .html, .shtml or .xhtml.

Does helm-ag support such arguments?

**Comment by syohex** [comment]
If you use `helm-ag` command, you can command line option as below.

![helm-ag-option](https://cloud.githubusercontent.com/assets/554281/9594686/4761f8b0-5099-11e5-97ce-682bcc85f95a.gif)

If you use `helm-do-ag` command, you can use minus prefix(`M--`, `C--`) for specifying extra command line options as below. You cannot use this way with `helm-projectile-ag` because helm-projectile uses prefix argument for other purpose.

![helm-do-ag-option](https://cloud.githubusercontent.com/assets/554281/9594697/6b6cc032-5099-11e5-8f21-6169ca085bf8.gif)

And if you set `helm-ag-always-set-extra-option` to non-nil, helm-do-ag always asks you about extra options. You can use this flag with helm-projectile.
