### ISSUE TITLE
Using helm-ag instead of helm-find

### ISSUE THREAD

**Issue by bmag** [syohex/emacs-helm-ag#172]
Hi, I'm trying to use helm-ag to search for files, similar to how helm-find can be used. So basically, what I want is an interface to "ag -g".

I was almost able to get the wanted behaviour by calling `helm-ag` and entering "-g" when prompted for a pattern, but this doesn't allow me to specify the directory in which I want to search for files.

The closest I could get to implementing what I want is this, but it's kind of a hack (and `flet` is obsolete since 24.3):
```elisp
(defun helm-ag-files (&optional basedir)
  "Search for files under BASEDIR."
  (interactive "DFind files in directory: \n")
  (flet ((helm-ag--query () (setq helm-ag--last-query "-g")))
    (helm-ag basedir)))
```

Is there a chance you will implement such a command? I am not sure what would be the correct way to implement it myself.

**Comment by syohex** [comment]
> I was almost able to get the wanted behaviour by calling helm-ag and entering "-g" when prompted for a pattern, but this doesn't allow me to specify the directory in which I want to search for files.

Please use `C-u` prefix argument. Then helm-ag asks you searched directory

> Is there a chance you will implement such a command?

No. You want to use such command, please add it to your init.el.

BTW `ag` has issue about parsing ignore file such as `.gitignore`. Some files may not be listed when `.gitignore` has NOT pattern, e.g `!foobar`(And it seems there are some issues about ignore files). So I suppose `ag` should not be used for finding file now. I think it is better to use [helm-ls-git](https://github.com/emacs-helm/helm-ls-git) instead of ag based command.
